[template]
prefix="/_VMS_BUCKET_"
src = "vms-service.tmpl"
dest = "/etc/fk-vms-service/config/vms-service-config.yml"
keys = ["/database.driverClass",
"/database.user",
"/database.password",
"/database.url",
"/database.maxWaitForConnection",
"/database.minSize",
"/database.maxSize",
"/server.minThreads",
"/server.maxThreads",
"/server.maxQueuedRequests",
"/server.idleThreadTimeout",
"/server.shutdownGracePeriod",
"/server.rootPath",
"/server.adminContextPath",
"/server.applicationContextPath",
"/server.type",
"/server.adminMinThreads",
"/server.adminMaxThreads",
"/server.applicationConnectors.0.type",
"/server.applicationConnectors.0.port",
"/server.applicationConnectors.0.headerCacheSize",
"/server.applicationConnectors.0.outputBufferSize",
"/server.applicationConnectors.0.maxRequestHeaderSize",
"/server.applicationConnectors.0.maxResponseHeaderSize",
"/server.applicationConnectors.0.inputBufferSize",
"/server.applicationConnectors.0.idleTimeout",
"/server.applicationConnectors.0.minBufferPoolSize",
"/server.applicationConnectors.0.bufferPoolIncrement",
"/server.applicationConnectors.0.maxBufferPoolSize",
"/server.applicationConnectors.0.acceptorThreads",
"/server.applicationConnectors.0.selectorThreads",
"/server.applicationConnectors.0.acceptQueueSize",
"/server.applicationConnectors.0.reuseAddress",
"/server.applicationConnectors.0.soLingerTime",
"/server.applicationConnectors.0.useServerHeader",
"/server.applicationConnectors.0.useDateHeader",
"/server.applicationConnectors.0.useForwardedHeaders",
"/server.adminConnectors.0.type",
"/server.adminConnectors.0.port",
"/server.requestLog.appenders.0.type",
"/server.requestLog.appenders.0.currentLogFilename",
"/server.requestLog.appenders.0.timeZone",
"/server.requestLog.appenders.0.logFormat",
"/server.requestLog.appenders.0.archive",
"/server.requestLog.appenders.0.archivedLogFilenamePattern",
"/server.requestLog.appenders.0.archivedFileCount",
"/logging.level",
"/logging.loggers.io.dropwizard",
"/logging.loggers.org.eclipse.jetty",
"/logging.loggers.com.flipkart.vms",
"/logging.loggers.org.skife.jdbi.v2",
"/logging.appenders.0.type",
"/logging.appenders.0.currentLogFilename",
"/logging.appenders.0.timeZone",
"/logging.appenders.0.logFormat",
"/logging.appenders.0.archive",
"/logging.appenders.0.archivedLogFilenamePattern",
"/logging.appenders.0.archivedFileCount",
"/swaggerBundleConfiguration.resourcePackage",
"/redisConfig.redisMasterName",
"/categoryServiceConfig.hostname",
"/categoryServiceConfig.port",
"/redisConfig.poolConfig.maxIdle",
"/redisConfig.poolConfig.maxTotal",
"/redisConfig.poolConfig.maxWaitMillis",
"/redisConfig.poolConfig.minIdle",
"/redisConfig.poolConfig.testOnBorrow",
"/redisConfig.sentinelHosts",
"/redisConfig.timeout",
"/noFrillsRedisConfig.redisMasterName",
"/noFrillsRedisConfig.poolConfig.maxIdle",
"/noFrillsRedisConfig.poolConfig.maxTotal",
"/noFrillsRedisConfig.poolConfig.maxWaitMillis",
"/noFrillsRedisConfig.poolConfig.minIdle",
"/noFrillsRedisConfig.poolConfig.testOnBorrow",
"/noFrillsRedisConfig.sentinelHosts",
"/noFrillsRedisConfig.timeout",
"/rulesRedisNotificationsConfig.redisMasterName",
"/rulesRedisNotificationsConfig.redisPassword",
"/rulesRedisNotificationsConfig.poolConfig.maxIdle",
"/rulesRedisNotificationsConfig.poolConfig.maxTotal",
"/rulesRedisNotificationsConfig.poolConfig.maxWaitMillis",
"/rulesRedisNotificationsConfig.poolConfig.minIdle",
"/rulesRedisNotificationsConfig.poolConfig.testOnBorrow",
"/rulesRedisNotificationsConfig.sentinelHosts",
"/rulesRedisNotificationsConfig.timeout",
"/flywayConfig.locations",
"/flywayConfig.sqlMigrationPrefix",
"/flywayConfig.baselineOnMigrate",
"/spcmsServiceConfig.hostname",
"/spcmsServiceConfig.port",
"/varadhiConfig.appId",
"/varadhiConfig.exchangeName",
"/varadhiConfig.exchangeType",
"/varadhiConfig.userName",
"/jerseyClientConfig.timeout",
"/jerseyClientConfig.connectionTimeout",
"/jerseyClientConfig.timeToLive",
"/jerseyClientConfig.cookiesEnabled",
"/jerseyClientConfig.maxConnections",
"/jerseyClientConfig.maxConnectionsPerRoute",
"/jerseyClientConfig.minThreads",
"/jerseyClientConfig.maxThreads",
"/jerseyClientConfig.workQueueSize",
"/jerseyClientConfig.gzipEnabled",
"/jerseyClientConfig.gzipEnabledForRequests",
"/jerseyClientConfig.chunkedEncodingEnabled",
"/hyperionAuditConfig.environment",
"/hyperionAuditConfig.appName",
"/hyperionAuditConfig.hyperionHost",
"/hyperionAuditConfig.hyperionPort",
"/fdpConfig.pushEventsSwitch",
"/fdpConfig.verticalEventSchemaVersion",
"/fdpConfig.attributeVerticalSchemaVersion",
"/fdpConfig.verticalEntitySchemaVersion",
"/fdpConfig.attributeVerticalCreateUpdateSchemaVersion",
"/fdpConfig.verticalCreateUpdateSchemaVersion",
"/orientdbConfig.user",
"/orientdbConfig.password",
"/orientdbConfig.connectionMode",
"/orientdbConfig.host",
"/orientdbConfig.databaseName",
"/orientdbConfig.minPoolSize",
"/orientdbConfig.maxPoolSize",
"/orientdbConfig.databaseUser",
"/orientdbConfig.databasePassword",
"/metadataConfig.metadataTypePath",
"/metadataConfig.processorDefinitionPath",
"/migrationConfig.metadataTypes",
"/versionState.state",
"/localisationServiceConfig.host",
"/localisationServiceConfig.port",
"/localisationServiceConfig.timeout",
"/vmsServiceConfig.host",
"/vmsServiceConfig.port",
"/vmsServiceConfig.queueName",
"/rosettaServiceConfig.host",
"/rosettaServiceConfig.port",
"/rosettaServiceConfig.prefix",
"/rosettaServiceConfig.connectionTimeout",
"/rosettaServiceConfig.socketTimeout",
"/rosettaServiceConfig.charset",
"/rosettaServiceConfig.maxConnections",
"/rosettaServiceConfig.maxPerRoute",
"/attributePropertiesConfig.changeNotAllowedProperties",
"/globalAttributesToSkip"]
